version: '3.9'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=SECRET_PASSWORD'
      - 'MYSQL_DATABASE=ddbt'
    volumes:
      - 'mariadb-data:/var/lib/mysql'

  app:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - django
    ports:
      - '8080:80'
    volumes:
      - './resources/nginx.conf:/etc/nginx/conf.d/default.conf'
      - 'django-static:/usr/share/nginx/html/static/'

  django:
    build:
      context: app
      args:
       - 'DBMS=mariadb'
    restart: always
    depends_on:
      - mariadb
    environment:
      - 'SQL_HOST=mariadb'
      - 'SQL_USER=mariadb'
      - 'SQL_PASSWORD=SECRET_PASSWORD'
      - 'SQL_DATABASE=ddbt'
      - 'ALLOWED_HOSTS=django'
      - 'DEBUG=1'
      - 'DISCORD_BOT_TOKEN='
      - 'OAUTH_CLIENT_ID='
      - 'OAUTH_CLIENT_SECRET='
      - 'OAUTH_URL='
      - 'PUBLIC_URL=localhost:8080'
    volumes:
      - 'django-static:/home/app/web/static'

volumes:
  mariadb-data:
  django-static:
